### ISSUE TITLE
question about the line 47 in allegro.py

### ISSUE THREAD

**Issue by Chenghao-Wu** [mariogeiger/allegro-jax#1]
Hi Mario, thank you very much for the project!

When I read the code, I am a bit confused about the line 47 of allegro.py, should the number of the neurons of w be the num_irreps of V rather than its mul_gcd?

**Comment by mariogeiger** [comment]
It's `mul_gcd` because of the `tensor_product` and `.mul_to_axis` of line 54.

Let me add the shapes in comments for clarity
```python
w = e3nn.flax.MultiLayerPerceptron((V.irreps.mul_gcd,))(x)
# x.shape = (num_edges, V.irreps.mul_gcd)

Y = e3nn.spherical_harmonics(range(self.max_ell + 1), vectors, True)
wY = e3nn.scatter_sum(
    w[:, :, None] * Y[:, None, :], dst=senders, map_back=True
) / jnp.sqrt(self.avg_num_neighbors)
assert wY.shape == (num_edges, V.irreps.mul_gcd, wY.irreps.dim)

# Here you need wY and V.mul_to_axis() to be of compatible shapes
V = e3nn.tensor_product(
    wY,              # shape = (num_edges, V.irreps.mul_gcd, irreps dimension)
    V.mul_to_axis(), # shape = (num_edges, V.irreps.mul_gcd, irreps dimension (different))
    filter_ir_out="0e" + irreps_out #      ^^^^^^^^^^^^^--- we need the same here
).axis_to_mul()
```

PS: most of the time all the multiplicities of `V` are equal (for instance `32x1o + 32x1e + 32x2e`, `V.irreps.mul_gcd = 32`)

**Comment by Chenghao-Wu** [comment]
Hi Mario, thank you very much for your explanations! 
I was a bit confused previously. The comments are indeed very helpful, and it is clear to me now.

Thank you again!
